{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "from pylab import *\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Homework 3: ISM Dynamics\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Part I: 3-phase SNR remnant model\n",
    "We're going to construct a three phase supernova remnant model based on what we learned in class, solving for the radius and velocity of the remnant front and then use it ask questions about ISM dynamics\n",
    "Below is the a `SN` class object initialized based on the initial supernova energy, the mass ejected, and the ambient conditions of the interstellar medium. Looking at the `__init__` function, you should see that we are initializing an array in time and will be filling in arrays of the shock front velocity and the shock front radius that correspond to those times. \n",
    "Each phase of the supernova expansion has a solution for the front velocity and the front radius and a corresponding condition at which the phase ends. For each phase, we will write a function that solves for the velocity, radius, and corresponding limit over which the solutions apply, filling in the array when that condition is met. Each solution needs to be properly normalized so that it matches its value at the end of the previous phase. \n",
    "\n",
    "As an example for what the function should do, the `free_expansion` phase function has been written for you. Note that the function fills the appropriate solution for `v_f` in units of $km/s$, `R_f` in units of $pc$ for the range of indices `imin` to `imax` over which the solution is valid. The index of the transition point is then stored so that it can be used to define `imin` for the subsequent function.\n",
    "\n",
    "### a. \n",
    "Fill in the function for the energy conserving phase as the `blast_wave` function. Recall that the condition for the end of the energy conserving phase is when the post-shock temperature $T < 10^6 \\mathrm{K}$. \n",
    "\n",
    "### b. \n",
    "Fill in the function for the momentum conserving phase as the `snow_plow` function. Recall that the condition for the end of the momentum conserving phase occurs when the velocity is on par with the ambient sound speed. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "Msun = 1.99e33 #mass of sun in grams\n",
    "cmtokm = 1e-5 #conversion from cm to km\n",
    "yrtos = 3.154e7 #seconds in year\n",
    "mH = 1.67e-24 #mass of a hydrogen atom in grams\n",
    "pctocm = 3.086e18 #cm in a parsec\n",
    "\n",
    "class SN:\n",
    "    def __init__(self,E0=10**51, M0=1.0, rho_amb=1*mH,T_amb=100.):\n",
    "        self.E0 = E0\n",
    "        self.v0 = np.sqrt(2.*E0/(M0*Msun)) #velocity of ejecta in cm/s\n",
    "        self.M0 = M0*Msun # mass of the ejecta\n",
    "        self.time = np.logspace(-1,9,100,dtype='float') #time in yrs\n",
    "        self.v_f = np.zeros_like(self.time) #empty arrays for the velocity of the front over time, units of km/s\n",
    "        self.R_f = np.zeros_like(self.time) #empty arrays for the radius of the front over time, units of pc\n",
    "        self.rho_amb = rho_amb #ambient medium density in g/cm^3\n",
    "        self.i_bc = [0,0,0] # to record the index of the arrays at which each phase ends\n",
    "        self.cs_amb = 0.3*np.sqrt(T_amb/10.) # ambient sound speed in km/s\n",
    "        \n",
    "    def free_expansion(self):\n",
    "        imin = 0 #index of the start of the phase\n",
    "        v_free = self.v0*np.ones_like(self.time)\n",
    "        r_free = v_free*self.time*yrtos\n",
    "        r_lim = (3*self.M0/4./pi/self.rho_amb)**(1./3.)\n",
    "        imax = np.argmin(np.abs(r_free-r_lim)) # index of the end of the phase\n",
    "        self.v_f[imin:imax] = v_free[imin:imax]*cmtokm #in km/s\n",
    "        self.R_f[imin:imax] = r_free[imin:imax]/pctocm #in pc\n",
    "        self.i_bc[0] = imax-1 #record transition point\n",
    "        \n",
    "    def blast_wave(self):\n",
    "        imin = self.i_bc[0]\n",
    "        v_bw = (self.time)**(-3/5)\n",
    "        r_bw = ((self.E0/self.rho_amb)*(self.time**0.5))**(1/5)\n",
    "        imax = np.argmax(self.time > r_bw) \n",
    "\n",
    "        self.v_f[imin:imax] = v_bw[imin:imax]*cmtokm\n",
    "        self.R_f[imin:imax] = r_bw[imin:imax]/pctocm\n",
    "        self.i_bc[1] = imax-1\n",
    "        \n",
    "    def snow_plow(self): #using equations from trhe textbook\n",
    "        imin = self.i_bc[1]\n",
    "\n",
    "        v_sp = self.v_f*(self.R_f/r_free)**3\n",
    "        r_sp = self.R_f + (4*self.v_f*(self.R_f**3)*(self.time))**(1/4)\n",
    "        imax = np.argmax(self.v_f > self.cs_amb) #end of phase is when v is around c_s - indistinguishable from ISM\n",
    "        \n",
    "        self.v_f[imin:imax] = v_sp[imin:imax]\n",
    "        self.R_f[imin:imax] = r_sp[imin:imax]\n",
    "        self.i_bc[2] = imax-1\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### part c.\n",
    "When you're happy with the solutions you've developed, run your model for the default choice of input parameters. Plot the solution and label the three phases of the solution. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error in callback <function _draw_all_if_interactive at 0x11496c220> (for post_execute):\n",
      "Unexpected exception formatting exception. Falling back to standard exception\n",
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/events.py\", line 89, in trigger\n",
      "    )\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/pyplot.py\", line 120, in _draw_all_if_interactive\n",
      "    from matplotlib.quiver import Barbs, Quiver, QuiverKey\n",
      "        ^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/_pylab_helpers.py\", line 132, in draw_all\n",
      "    manager.canvas.draw_idle()\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backend_bases.py\", line 2082, in draw_idle\n",
      "    format : str, optional\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 388, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 95, in draw_wrapper\n",
      "    result = draw(artist, renderer, *args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/figure.py\", line 3140, in draw\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/image.py\", line 131, in _draw_list_compositing_images\n",
      "    for a in artists:\n",
      "        ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/axes/_base.py\", line 3064, in draw\n",
      "    else:\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/image.py\", line 131, in _draw_list_compositing_images\n",
      "    for a in artists:\n",
      "        ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/axis.py\", line 1380, in draw\n",
      "    def draw(self, renderer, *args, **kwargs):\n",
      "            ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/axis.py\", line 301, in draw\n",
      "    \"\"\"\n",
      "        \n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/text.py\", line 800, in draw\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 190, in draw_text\n",
      "    return self.draw_mathtext(gc, x, y, s, prop, angle)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 178, in draw_mathtext\n",
      "    self.mathtext_parser.parse(s, self.dpi, prop,\n",
      "TypeError: MathTextParser.parse() got an unexpected keyword argument 'antialiased'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 2105, in showtraceback\n",
      "    try:\n",
      "         \n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1396, in structured_traceback\n",
      "    out=None, tb_offset=None):\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1287, in structured_traceback\n",
      "    It can thus be used as a sys.excepthook for Python > 2.1.\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1140, in structured_traceback\n",
      "    except OSError:\n",
      "                    \n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1055, in format_exception_as_a_whole\n",
      "    etype = etype.__name__  # type: ignore\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 955, in format_record\n",
      "    \"\".join(\n",
      "        ^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 778, in lines\n",
      "    # self.lines = []\n",
      "           ^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/core.py\", line 698, in lines\n",
      "    pieces = self.included_pieces\n",
      "             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/core.py\", line 649, in included_pieces\n",
      "    pos = scope_pieces.index(self.executing_piece)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/core.py\", line 628, in executing_piece\n",
      "    return only(\n",
      "           ^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/executing/executing.py\", line 164, in only\n",
      "    raise NotOneValueFound('Expected one value, found 0')\n",
      "executing.executing.NotOneValueFound: Expected one value, found 0\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/formatters.py\", line 223, in catch_format_error\n",
      "    r = method(self, *args, **kwargs)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/formatters.py\", line 340, in __call__\n",
      "    return printer(obj)\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/pylabtools.py\", line 152, in print_figure\n",
      "    fig.canvas.print_figure(bytes_io, **kw)\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backend_bases.py\", line 2366, in print_figure\n",
      "    Interactive backends should implement this in a more native way.\n",
      "                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backend_bases.py\", line 2232, in <lambda>\n",
      "    \"\"\"\n",
      "        \n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 497, in print_png\n",
      "    self._print_pil(filename_or_obj, \"png\", pil_kwargs, metadata)\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 445, in _print_pil\n",
      "    FigureCanvasAgg.draw(self)\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 388, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 95, in draw_wrapper\n",
      "    result = draw(artist, renderer, *args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/figure.py\", line 3140, in draw\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/image.py\", line 131, in _draw_list_compositing_images\n",
      "    for a in artists:\n",
      "        ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/axes/_base.py\", line 3064, in draw\n",
      "    else:\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/image.py\", line 131, in _draw_list_compositing_images\n",
      "    for a in artists:\n",
      "        ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/axis.py\", line 1380, in draw\n",
      "    def draw(self, renderer, *args, **kwargs):\n",
      "            ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/axis.py\", line 301, in draw\n",
      "    \"\"\"\n",
      "        \n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/text.py\", line 800, in draw\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 190, in draw_text\n",
      "    return self.draw_mathtext(gc, x, y, s, prop, angle)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 178, in draw_mathtext\n",
      "    self.mathtext_parser.parse(s, self.dpi, prop,\n",
      "TypeError: MathTextParser.parse() got an unexpected keyword argument 'antialiased'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 2105, in showtraceback\n",
      "    try:\n",
      "         \n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1396, in structured_traceback\n",
      "    out=None, tb_offset=None):\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1287, in structured_traceback\n",
      "    It can thus be used as a sys.excepthook for Python > 2.1.\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1140, in structured_traceback\n",
      "    except OSError:\n",
      "                    \n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1055, in format_exception_as_a_whole\n",
      "    etype = etype.__name__  # type: ignore\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 955, in format_record\n",
      "    \"\".join(\n",
      "        ^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 778, in lines\n",
      "    # self.lines = []\n",
      "           ^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/core.py\", line 698, in lines\n",
      "    pieces = self.included_pieces\n",
      "             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/core.py\", line 649, in included_pieces\n",
      "    pos = scope_pieces.index(self.executing_piece)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/core.py\", line 628, in executing_piece\n",
      "    return only(\n",
      "           ^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/executing/executing.py\", line 164, in only\n",
      "    raise NotOneValueFound('Expected one value, found 0')\n",
      "executing.executing.NotOneValueFound: Expected one value, found 0\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<Figure size 450x900 with 2 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "snr = SN()\n",
    "snr.free_expansion()\n",
    "snr.blast_wave()\n",
    "snr.snow_plow()\n",
    "\n",
    "f,ax=subplots(2,constrained_layout=True, dpi=150,sharex=True)\n",
    "f.set_size_inches(3,6)\n",
    "ax[0].loglog(snr.time,snr.R_f)\n",
    "ax[1].loglog(snr.time,snr.v_f)\n",
    "ax[1].set_xlabel('time [yrs]')\n",
    "ax[0].set_ylabel('R [pc]')\n",
    "ax[1].set_ylabel('v [km/s]')\n",
    "\n",
    "for a in ax:\n",
    "    a.axvline(snr.time[snr.i_bc[0]],color='gray',ls='dotted',lw=1)\n",
    "    a.axvline(snr.time[snr.i_bc[1]],color='gray',ls='dotted',lw=1)\n",
    "    a.axvline(snr.time[snr.i_bc[2]],color='gray',ls='dotted',lw=1)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### part d.\n",
    "Run the remnant model for three different types of ISM conditions and plot them all on the same plot.\n",
    "1. Warm Neutral Medium\n",
    "2. Cold Neutral Medium\n",
    "3. Molecular Cloud \n",
    "\n",
    "Describe the main differences across these these different environments in terms of the remnant properties. In terms of the basic understanding of shocks we built up in class, why does this behavior hold?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.legend.Legend at 0x1254ef050>"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error in callback <function _draw_all_if_interactive at 0x11496c220> (for post_execute):\n",
      "Unexpected exception formatting exception. Falling back to standard exception\n",
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/events.py\", line 89, in trigger\n",
      "    )\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/pyplot.py\", line 120, in _draw_all_if_interactive\n",
      "    from matplotlib.quiver import Barbs, Quiver, QuiverKey\n",
      "        ^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/_pylab_helpers.py\", line 132, in draw_all\n",
      "    manager.canvas.draw_idle()\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backend_bases.py\", line 2082, in draw_idle\n",
      "    format : str, optional\n",
      "            ^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 388, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 95, in draw_wrapper\n",
      "    result = draw(artist, renderer, *args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/figure.py\", line 3140, in draw\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/image.py\", line 131, in _draw_list_compositing_images\n",
      "    for a in artists:\n",
      "        ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/axes/_base.py\", line 3064, in draw\n",
      "    else:\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/image.py\", line 131, in _draw_list_compositing_images\n",
      "    for a in artists:\n",
      "        ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/axis.py\", line 1380, in draw\n",
      "    def draw(self, renderer, *args, **kwargs):\n",
      "            ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/axis.py\", line 301, in draw\n",
      "    \"\"\"\n",
      "        \n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/text.py\", line 800, in draw\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 190, in draw_text\n",
      "    return self.draw_mathtext(gc, x, y, s, prop, angle)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 178, in draw_mathtext\n",
      "    self.mathtext_parser.parse(s, self.dpi, prop,\n",
      "TypeError: MathTextParser.parse() got an unexpected keyword argument 'antialiased'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 2105, in showtraceback\n",
      "    try:\n",
      "         \n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1396, in structured_traceback\n",
      "    out=None, tb_offset=None):\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1287, in structured_traceback\n",
      "    It can thus be used as a sys.excepthook for Python > 2.1.\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1140, in structured_traceback\n",
      "    except OSError:\n",
      "                    \n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1055, in format_exception_as_a_whole\n",
      "    etype = etype.__name__  # type: ignore\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 955, in format_record\n",
      "    \"\".join(\n",
      "        ^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 778, in lines\n",
      "    # self.lines = []\n",
      "           ^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/core.py\", line 698, in lines\n",
      "    pieces = self.included_pieces\n",
      "             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/core.py\", line 649, in included_pieces\n",
      "    pos = scope_pieces.index(self.executing_piece)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/core.py\", line 628, in executing_piece\n",
      "    return only(\n",
      "           ^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/executing/executing.py\", line 164, in only\n",
      "    raise NotOneValueFound('Expected one value, found 0')\n",
      "executing.executing.NotOneValueFound: Expected one value, found 0\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/formatters.py\", line 223, in catch_format_error\n",
      "    r = method(self, *args, **kwargs)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/formatters.py\", line 340, in __call__\n",
      "    return printer(obj)\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/pylabtools.py\", line 152, in print_figure\n",
      "    fig.canvas.print_figure(bytes_io, **kw)\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backend_bases.py\", line 2366, in print_figure\n",
      "    Interactive backends should implement this in a more native way.\n",
      "                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backend_bases.py\", line 2232, in <lambda>\n",
      "    \"\"\"\n",
      "        \n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 497, in print_png\n",
      "    self._print_pil(filename_or_obj, \"png\", pil_kwargs, metadata)\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 445, in _print_pil\n",
      "    FigureCanvasAgg.draw(self)\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 388, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 95, in draw_wrapper\n",
      "    result = draw(artist, renderer, *args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/figure.py\", line 3140, in draw\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/image.py\", line 131, in _draw_list_compositing_images\n",
      "    for a in artists:\n",
      "        ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/axes/_base.py\", line 3064, in draw\n",
      "    else:\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/image.py\", line 131, in _draw_list_compositing_images\n",
      "    for a in artists:\n",
      "        ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/axis.py\", line 1380, in draw\n",
      "    def draw(self, renderer, *args, **kwargs):\n",
      "            ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/axis.py\", line 301, in draw\n",
      "    \"\"\"\n",
      "        \n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/text.py\", line 800, in draw\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 190, in draw_text\n",
      "    return self.draw_mathtext(gc, x, y, s, prop, angle)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 178, in draw_mathtext\n",
      "    self.mathtext_parser.parse(s, self.dpi, prop,\n",
      "TypeError: MathTextParser.parse() got an unexpected keyword argument 'antialiased'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 2105, in showtraceback\n",
      "    try:\n",
      "         \n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1396, in structured_traceback\n",
      "    out=None, tb_offset=None):\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1287, in structured_traceback\n",
      "    It can thus be used as a sys.excepthook for Python > 2.1.\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1140, in structured_traceback\n",
      "    except OSError:\n",
      "                    \n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1055, in format_exception_as_a_whole\n",
      "    etype = etype.__name__  # type: ignore\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 955, in format_record\n",
      "    \"\".join(\n",
      "        ^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 778, in lines\n",
      "    # self.lines = []\n",
      "           ^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/core.py\", line 698, in lines\n",
      "    pieces = self.included_pieces\n",
      "             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/core.py\", line 649, in included_pieces\n",
      "    pos = scope_pieces.index(self.executing_piece)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/core.py\", line 628, in executing_piece\n",
      "    return only(\n",
      "           ^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/executing/executing.py\", line 164, in only\n",
      "    raise NotOneValueFound('Expected one value, found 0')\n",
      "executing.executing.NotOneValueFound: Expected one value, found 0\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<Figure size 300x600 with 2 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "f,ax=subplots(2,constrained_layout=True, dpi=100,sharex=True)\n",
    "f.set_size_inches(3,6)\n",
    "ax[1].set_xlabel('time [yrs]')\n",
    "ax[0].set_ylabel('R [pc]')\n",
    "ax[1].set_ylabel('v [km/s]')\n",
    "\n",
    "#textbook + notes values\n",
    "rho_WNM = mH/1e8 #g cm^-3, average grain size\n",
    "T_WNM = 8000 #K\n",
    "rho_CNM = mH/1e10 #m^-3, nH from textbook\n",
    "T_CNM = 100 #K\n",
    "rho_mol = \n",
    "T_mol = 10 #K\n",
    "cond1 = {'rho_amb': rho_WNM, 'T_amb': T_WNM,'label':'WNM'}\n",
    "cond2 = {'rho_amb': rho_CNM, 'T_amb': T_CNM,'label':'CNM'}\n",
    "#cond3 = {'rho_amb': rho_mol, 'T_amb': T_mol, 'label':'mol. cloud'}\n",
    "\n",
    "for cond in [cond1,cond2]: #cond3\n",
    "    snr = SN(rho_amb=cond['rho_amb'],T_amb=cond['T_amb'])\n",
    "    snr.free_expansion()\n",
    "    snr.blast_wave()\n",
    "    snr.snow_plow()\n",
    "\n",
    "    ax[0].loglog(snr.time,snr.R_f,label=cond['label'])\n",
    "    ax[1].loglog(snr.time,snr.v_f)\n",
    "    \n",
    "ax[0].legend()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### part e.\n",
    "\n",
    "Now run the remnant model but varying the progenitor mass. Make a similar plot. Based on the plot, what is more important for determining the remnant properties, the supernova progenitor's environment or the supernova progenitor's properties?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "f,ax=subplots(2,constrained_layout=True, dpi=100,sharex=True)\n",
    "f.set_size_inches(3,6)\n",
    "ax[1].set_xlabel('time [yrs]')\n",
    "ax[0].set_ylabel('R [pc]')\n",
    "ax[1].set_ylabel('v [km/s]')\n",
    "\n",
    "#cond1 = {'M0': 1.4, 'label': '1.4 Msun'}\n",
    "\n",
    "\n",
    "#for cond in [cond1,cond2,cond3]:\n",
    "#    snr = SN(M0 = cond['M0'])\n",
    "#    snr.free_expansion()\n",
    "#    snr.blast_wave()\n",
    "#    snr.snow_plow()\n",
    "\n",
    "#    ax[0].loglog(snr.time,snr.R_f,label=cond['label'])\n",
    "#    ax[1].loglog(snr.time,snr.v_f)\n",
    "    \n",
    "#ax[0].legend()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Part II: Thinking about Turbulence\n",
    "\n",
    "We talked pretty generally about ways we can generate turbulence in the ISM. Today we're going to think about how turbulence is quantified.\n",
    "\n",
    "In the standard fluid dynamical picture, a flow is judged to be turbulent by the ratio of its inertial forces to its viscous ones. Fluid viscosity usually refers to the amount of intramolecular friction a fluid has, which is a behavior that is dependent on the fluid composition but also it's temperature and density. The more viscous a fluid is the more it damps out fluctuations that could become grow to become turbulent, so it generally moves more smoothly (a.k.a. as a laminar flow) at the same amount of agitation e.g. think how easy it is to create ripples and frothing in water by stirring vs in honey. \n",
    "\n",
    "The ratio of inertial forces to viscous ones is defined as the Reynolds Number $Re$, which you can derive by taking the ratio of the advection forces in the momentum equation to the viscous ones. Simplified by dimensional analysis, it is usually evaluated as a characteristic fluid velocity $u$, a characteristic length scale $R$, and the kinematic viscosity $\\nu$. \n",
    "\n",
    "$Re = \\frac{\\mathrm{Inertial \\ Forces}}{\\mathrm{Viscous \\ Forces}} = \\frac{\\rho u \\cdot \\nabla u}{\\rho \\nu \\nabla^2 u} \\sim \\frac{u R}{\\nu}$\n",
    "\n",
    "When $Re \\gtrsim 5000-10000$, the flow is considered turbulent.\n",
    "\n",
    "The kinematic viscosity then has units of $v \\times L$, which is often considered to encode the velocity of the smallest fluctuations times the length scale of the mean free-path $\\lambda = 1/n\\sigma$ between molecules. Where $n$ is the number density of atoms and $\\sigma$ is the interaction cross-section. \n",
    "\n",
    "or: \n",
    "\n",
    "$\\nu = \\frac{u_t}{n \\sigma}$\n",
    "\n",
    "where estimates will say that $u_t = c_s$ is the velocity of fluctuations at the smallest scales i.e. the sound speed and $n$ is the number density of hydrogen atoms, and $\\sigma = 10^{-15} cm^{2}$, which the area of an atom (e.g. the Bohr radius is $\\sim 10^{-8} cm$.) \n",
    "\n",
    "### part a.\n",
    "\n",
    "Define a function to calculate the Reynold's number for a flow given a characteristic flow velocity, characteristic flow length scale, temperature, and density.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [],
   "source": [
    "sigma = 1e-15 #cm^2\n",
    "def Re(u,R,T,rho):\n",
    "    c_s = T**0.5 #sound speed proportionality from notes\n",
    "    nu = c_s/rho*sigma #viscosity (Pa*s?)\n",
    "    Reynolds = u*R/nu\n",
    "    return Reynolds"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### part b.\n",
    "\n",
    "Typically, the characteristic velocity and length scales are considered to be the characteristic scales of the flow -- the scales at most of the energy is being injected.\n",
    "For example, shear flow is the most common system for looking at turbulence generation, where one side of the flow is slower than the other side of the flow and fluctuations build up at the boundary (for a physical picture, think of how airplane turbulence forms at the surface of the wing of the plane where it cuts through the incoming air, or at pipe edges where it is being slowed down by friction with the pipe surface). For a pipe, for example, the characteristic velocity is the average flow speed and the characteristic length is the pipe radius. \n",
    "\n",
    "(There are many nice fluid dynamical resources online for building intuition about this, which would make good resource contributions for anyone who wants to write about them)\n",
    "\n",
    "Anyway, in our toy model, we're going to try to see what the Reynold's numbers are like for different types of assumptions regarding the scale and physical conditions of our flow. \n",
    "Using your function in part a, plot the Reynolds number as a function of length scale (let's say from 0.01 to 100 pc). Take the characteristic velocity to be the velocities measured by Larson's Law as a function of length scale. \n",
    "\n",
    "Plot this for :\n",
    "1. WNM density and temperature conditions\n",
    "2. CNM density and temperature conditions\n",
    "\n",
    "According to this plot, for a threshold Reynolds number of 10000, what is the corresponding length scale for turbulent energy injection for each phase in order to reproduce observed velocity dispersions?\n",
    "\n",
    "Does a hotter medium require shear on a larger or smaller scale than a colder medium?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/formatters.py\", line 223, in catch_format_error\n",
      "    r = method(self, *args, **kwargs)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/formatters.py\", line 340, in __call__\n",
      "    return printer(obj)\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/pylabtools.py\", line 152, in print_figure\n",
      "    fig.canvas.print_figure(bytes_io, **kw)\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backend_bases.py\", line 2366, in print_figure\n",
      "    Interactive backends should implement this in a more native way.\n",
      "                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backend_bases.py\", line 2232, in <lambda>\n",
      "    \"\"\"\n",
      "        \n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 497, in print_png\n",
      "    self._print_pil(filename_or_obj, \"png\", pil_kwargs, metadata)\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 445, in _print_pil\n",
      "    FigureCanvasAgg.draw(self)\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 388, in draw\n",
      "    self.figure.draw(self.renderer)\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 95, in draw_wrapper\n",
      "    result = draw(artist, renderer, *args, **kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/figure.py\", line 3140, in draw\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/image.py\", line 131, in _draw_list_compositing_images\n",
      "    for a in artists:\n",
      "        ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/axes/_base.py\", line 3064, in draw\n",
      "    else:\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/image.py\", line 131, in _draw_list_compositing_images\n",
      "    for a in artists:\n",
      "        ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/axis.py\", line 1380, in draw\n",
      "    def draw(self, renderer, *args, **kwargs):\n",
      "            ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/axis.py\", line 301, in draw\n",
      "    \"\"\"\n",
      "        \n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/artist.py\", line 72, in draw_wrapper\n",
      "    return draw(artist, renderer)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/text.py\", line 800, in draw\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 190, in draw_text\n",
      "    return self.draw_mathtext(gc, x, y, s, prop, angle)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py\", line 178, in draw_mathtext\n",
      "    self.mathtext_parser.parse(s, self.dpi, prop,\n",
      "TypeError: MathTextParser.parse() got an unexpected keyword argument 'antialiased'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 2105, in showtraceback\n",
      "    try:\n",
      "         \n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1396, in structured_traceback\n",
      "    out=None, tb_offset=None):\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1287, in structured_traceback\n",
      "    It can thus be used as a sys.excepthook for Python > 2.1.\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1140, in structured_traceback\n",
      "    except OSError:\n",
      "                    \n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 1055, in format_exception_as_a_whole\n",
      "    etype = etype.__name__  # type: ignore\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 955, in format_record\n",
      "    \"\".join(\n",
      "        ^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/IPython/core/ultratb.py\", line 778, in lines\n",
      "    # self.lines = []\n",
      "           ^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/core.py\", line 698, in lines\n",
      "    pieces = self.included_pieces\n",
      "             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/core.py\", line 649, in included_pieces\n",
      "    pos = scope_pieces.index(self.executing_piece)\n",
      "                             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/utils.py\", line 145, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "                                               ^^^^^^^^^^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/stack_data/core.py\", line 628, in executing_piece\n",
      "    return only(\n",
      "           ^^^^^\n",
      "  File \"/Users/shirin/anaconda3/lib/python3.11/site-packages/executing/executing.py\", line 164, in only\n",
      "    raise NotOneValueFound('Expected one value, found 0')\n",
      "executing.executing.NotOneValueFound: Expected one value, found 0\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "L = np.logspace(-1,2,100)\n",
    "u_LL = sigma*yrtos/cmtokm #from notes\n",
    "\n",
    "Re_WNM = Re(u_LL, L, T_WNM, rho_WNM)\n",
    "Re_CNM = Re(u_LL, L, T_CNM, rho_CNM)\n",
    "\n",
    "fig, ax = plt.subplots()\n",
    "ax.loglog(L, Re_WNM, label='WNM')\n",
    "ax.loglog(L, Re_CNM, label='CNM')\n",
    "ax.axhline(1e4, color='gray', ls='dotted', label='Re = 10,000')\n",
    "ax.set_xlabel(\"R [pc]\")\n",
    "ax.set_ylabel('Reynolds Number')\n",
    "ax.legend()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "* Although I didn't get much time to work on this homework (due to other classes' exams taking time), I actually wish I had spent more time! I enjoyed part of it but was unable to actually get results due to some package/plotting issues? I'm not quite sure. I was totally unable to see plots. To generally answer the last question, based off of what I know about temperature and the velocity of molecules, I think it should be easier for molecules to be moving in a hotter environment, so a hotter fluid should require shear on a smaller scale than a colder fluid."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
